#!/usr/bin/env bash
# Configures an Ubuntu server with custom /etc/hosts

sudo sed -i 's/127\.0\.0\.1.*localhost/127.0.0.2    localhost/' /etc/hosts
echo "8.8.8.8    facebook.com" | sudo tee -a /etc/hosts > /dev/null
