#!/usr/bin/env bash
# Configures an Ubuntu server with custom /etc/hosts

sudo bash -c 'cat > /etc/hosts << EOF
127.0.0.2       localhost
8.8.8.8         facebook.com

# The following lines are desirable for IPv6 capable hosts
::1             localhost ip6-localhost ip6-loopback
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters
EOF'
